### PR TITLE
Explain devkit situation better

### PR DESCRIPTION
**Pull request by rnkovacs**

### CODE REVIEW

**Review by mo-beck — COMMENTED** [review]
Just a nit-pick:
"(available from 11.0.13), it needs to be downloaded separately"
Can we say that the kit is available starting 11.0.13?

**Comment by rnkovacs** [comment]
Well, I meant "this file" - the devkit generating script. Is that bit needed at all? Maybe it's more confusing than helpful. How about "Please note that this file is not yet present in the JDK 11.0.12 sources, it needs to be downloaded separately from the link provided. Once the port is upstreamed, this will no longer be necessary." ?

**Comment by karianna** [comment]
@rnkovacs - Can this be merged now?

**Comment by rnkovacs** [comment]
@karianna Yes, sorry for forgetting about this - it'll even get outdated very soon.

**Pull request merged**
